/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2026-01-05 09:54:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.product;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class read_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getInstance();
  _jspx_fnmap_0.mapFunction("fn:replace", org.apache.taglibs.standard.functions.Functions.class, "replace", new Class[] {java.lang.String.class, java.lang.String.class, java.lang.String.class});
  _jspx_fnmap_0.mapFunction("fn:substring", org.apache.taglibs.standard.functions.Functions.class, "substring", new Class[] {java.lang.String.class, int.class, int.class});
}

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("jar:file:/D:/works/SF/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/sp0/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664421078000L));
    _jspx_dependants.put("jar:file:/D:/works/SF/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/sp0/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fn-1_1.tld", Long.valueOf(1664421078000L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1764828089380L));
    _jspx_dependants.put("jar:file:/D:/works/SF/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/sp0/WEB-INF/lib/spring-security-taglibs-6.5.5.jar!/META-INF/security.tld", Long.valueOf(1758086692000L));
    _jspx_dependants.put("/WEB-INF/views/includes/footer.jsp", Long.valueOf(1767594467839L));
    _jspx_dependants.put("jar:file:/D:/works/SF/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/sp0/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fmt-1_1.tld", Long.valueOf(1664421078000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-6.5.5.jar", Long.valueOf(1766461423263L));
    _jspx_dependants.put("/WEB-INF/views/includes/header.jsp", Long.valueOf(1767605462963L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.release();
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\" />\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\n");
      out.write("  <title>Admin Panel</title>\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css\" rel=\"stylesheet\">\n");
      out.write("  \n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\">\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("  <!-- Top Navbar -->\n");
      out.write("  <header class=\"header\">\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-custom px-4\">\n");
      out.write("      <a class=\"navbar-brand\" href=\"/product/list\"><i class=\"bi bi-gear-fill me-2\"></i>관리자 페이지</a>\n");
      out.write("      <div class=\"collapse navbar-collapse\">\n");
      out.write("        <ul class=\"navbar-nav me-auto\">\n");
      out.write("          <li class=\"nav-item\"><a class=\"nav-link\" href=\"/product/list\">상품 리스트</a></li>\n");
      out.write("        </ul>\n");
      out.write("        <span class=\"navbar-text d-flex align-items-center gap-3\">\n");
      out.write("          <!-- 다크모드 토글 버튼 -->\n");
      out.write("          <button id=\"themeToggle\" class=\"btn btn-sm btn-outline-light\" title=\"테마 변경\">\n");
      out.write("            <span id=\"themeIcon\">🌙</span>\n");
      out.write("          </button>\n");
      out.write("          ");
      if (_jspx_meth_sec_005fauthorize_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        </span>\n");
      out.write("      </div>\n");
      out.write("    </nav>\n");
      out.write("  </header>\n");
      out.write("\n");
      out.write("  <!-- Sidebar + Content -->\n");
      out.write("  <div class=\"main-wrapper\">\n");
      out.write("    <!-- Sidebar -->\n");
      out.write("    <div class=\"sidebar pt-3\">\n");
      out.write("      <div class=\"list-group list-group-flush\">\n");
      out.write("        <a href=\"/product/list\" class=\"list-group-item active\">상품 리스트</a>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Main Content -->\n");
      out.write("    <div class=\"content\">    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container my-5\">\r\n");
      out.write("		<div class=\"row justify-content-center\">\r\n");
      out.write("			<div class=\"col-lg-6 col-md-8\">\r\n");
      out.write("				<div class=\"card shadow-sm border-0\" style=\"background:#fff;\">\r\n");
      out.write("					<div class=\"p-4 pb-0 text-center border-bottom\">\r\n");
      out.write("						<div class=\"mx-auto mb-3\" style=\"background:#f5f6fa;border-radius:12px;width:180px;height:180px;display:flex;align-items:center;justify-content:center;\">\r\n");
      out.write("							<img src=\"/resources/images/");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("\" alt=\"상품 이미지\" style=\"max-width:140px;max-height:140px;object-fit:contain;\" />\r\n");
      out.write("						</div>\r\n");
      out.write("						<h2 class=\"fw-bold mb-1\" style=\"font-size:2rem;letter-spacing:-1px;\">");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("</h2>\r\n");
      out.write("						<div class=\"mb-2\">\r\n");
      out.write("							<span class=\"badge bg-primary\" style=\"font-size:1em;\">");
      if (_jspx_meth_c_005fout_005f2(_jspx_page_context))
        return;
      out.write("</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"mb-2\">\r\n");
      out.write("							<span class=\"text-muted small\">상품번호 ");
      if (_jspx_meth_c_005fout_005f3(_jspx_page_context))
        return;
      out.write("</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<span class=\"fw-bold\" style=\"font-size:1.1rem;color:#222;\">₩ ");
      if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_page_context))
        return;
      out.write("</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"p-4\">\r\n");
      out.write("						<div class=\"mb-4\">\r\n");
      out.write("							<div class=\"text-secondary small mb-1\">상품설명</div>\r\n");
      out.write("							<div class=\"border rounded p-3 bg-light\" style=\"min-height:80px;\">\r\n");
      out.write("								");
      if (_jspx_meth_c_005fout_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"row g-2 mb-3\">\r\n");
      out.write("							<div class=\"col-6\">\r\n");
      out.write("								<div class=\"text-muted small\">작성자</div>\r\n");
      out.write("								<div class=\"fw-semibold\">");
      if (_jspx_meth_c_005fout_005f5(_jspx_page_context))
        return;
      out.write("</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-6\">\r\n");
      out.write("								<div class=\"text-muted small\">등록일</div>\r\n");
      out.write("								<div class=\"fw-semibold\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:replace(fn:substring(product.regdate, 0, 16), 'T', ' ')}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"d-flex gap-2 justify-content-end mt-4\">\r\n");
      out.write("								<a href='/product/list' class=\"btn btn-outline-primary px-4\">목록</a>\r\n");
      out.write("								<a href='/product/modify/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.num}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' class=\"btn btn-warning px-4\">수정</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"row justify-content-center mt-4\">\r\n");
      out.write("		<div class=\"col-lg-6 col-md-8\">\r\n");
      out.write("			<div class=\"card border-0 shadow-sm mb-4\">\r\n");
      out.write("				<div class=\"card-header bg-white border-bottom pb-2\">\r\n");
      out.write("					<strong>댓글</strong>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"card-body p-3\">\r\n");
      out.write("					<!-- 댓글 목록 -->\r\n");
      out.write("					<ul class=\"list-group mb-3\" id=\"replyList\">\r\n");
      out.write("						<!-- JS로 동적 렌더링 -->\r\n");
      out.write("					</ul>\r\n");
      out.write("					<!-- 댓글 입력 -->\r\n");
      out.write("					<form id=\"replyForm\" class=\"d-flex gap-2\">\r\n");
      out.write("						<input type=\"text\" id=\"replyText\" class=\"form-control\" maxlength=\"200\" placeholder=\"댓글을 입력하세요\" required>\r\n");
      out.write("						<input type=\"text\" id=\"replyer\" class=\"form-control\" maxlength=\"20\" placeholder=\"작성자\" required style=\"max-width:120px;\">\r\n");
      out.write("						<input type=\"hidden\" id=\"num\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.num}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("						<button type=\"submit\" class=\"btn btn-primary\">등록</button>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("		const productNum = document.getElementById('num').value;\r\n");
      out.write("\r\n");
      out.write("		// 댓글 목록 불러오기\r\n");
      out.write("		function loadReplies() {\r\n");
      out.write("		fetch('/reply/list/' + productNum)\r\n");
      out.write("			.then(res => res.json())\r\n");
      out.write("			.then(list => {\r\n");
      out.write("			const ul = document.getElementById('replyList');\r\n");
      out.write("			ul.innerHTML = '';\r\n");
      out.write("\r\n");
      out.write("			// 댓글이 없을 경우\r\n");
      out.write("			if (list.length === 0) {\r\n");
      out.write("				ul.innerHTML =\r\n");
      out.write("				'<li class=\"list-group-item text-center text-muted\">댓글이 없습니다.</li>';\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			// 댓글 목록 출력\r\n");
      out.write("			list.forEach(reply => {\r\n");
      out.write("				const li = document.createElement('li');\r\n");
      out.write("				li.className =\r\n");
      out.write("				'list-group-item d-flex justify-content-between align-items-center';\r\n");
      out.write("\r\n");
      out.write("				li.innerHTML = `\r\n");
      out.write("				<div>\r\n");
      out.write("					<span class=\"fw-semibold\">${reply.replyer}</span>\r\n");
      out.write("					<span class=\"text-muted small ms-2\">\r\n");
      out.write("					${reply.replydate ? new Date(reply.replydate).toISOString().substring(0, 10) : ''}\r\n");
      out.write("					</span><br>\r\n");
      out.write("					<span>${reply.replyText}</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<button\r\n");
      out.write("					class=\"btn btn-sm btn-outline-danger\"\r\n");
      out.write("					onclick=\"removeReply(${reply.rno})\">\r\n");
      out.write("					삭제\r\n");
      out.write("				</button>\r\n");
      out.write("				`;\r\n");
      out.write("\r\n");
      out.write("				ul.appendChild(li);\r\n");
      out.write("			});\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		// 댓글 등록 처리\r\n");
      out.write("		document\r\n");
      out.write("		.getElementById('replyForm')\r\n");
      out.write("		.addEventListener('submit', function (e) {\r\n");
      out.write("			e.preventDefault();\r\n");
      out.write("\r\n");
      out.write("			const replyText = document.getElementById('replyText').value.trim();\r\n");
      out.write("			const replyer = document.getElementById('replyer').value.trim();\r\n");
      out.write("\r\n");
      out.write("			// 입력값 검증\r\n");
      out.write("			if (!replyText || !replyer) return;\r\n");
      out.write("\r\n");
      out.write("			fetch('/reply/register', {\r\n");
      out.write("			method: 'POST',\r\n");
      out.write("			headers: { 'Content-Type': 'application/json' },\r\n");
      out.write("			body: JSON.stringify({\r\n");
      out.write("				replyText,\r\n");
      out.write("				replyer,\r\n");
      out.write("				num: productNum\r\n");
      out.write("			})\r\n");
      out.write("			})\r\n");
      out.write("			.then(res => res.json())\r\n");
      out.write("			.then(() => {\r\n");
      out.write("				document.getElementById('replyText').value = '';\r\n");
      out.write("				loadReplies();\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		// 댓글 삭제 처리\r\n");
      out.write("		function removeReply(rno) {\r\n");
      out.write("		if (!confirm('댓글을 삭제하시겠습니까?')) return;\r\n");
      out.write("	\r\n");
      out.write("		fetch('/reply/remove/' + rno, { method: 'POST' })\r\n");
      out.write("			.then(res => res.json())\r\n");
      out.write("			.then(() => loadReplies());\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("	  // 페이지 로드시 댓글 목록 호출\r\n");
      out.write("		loadReplies();\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- Footer -->\n");
      out.write("    <footer class=\"footer py-3 mt-auto text-center\">\n");
      out.write("      <span class=\"text-muted\">&copy; 2026 관리자 페이지. All rights reserved.</span>\n");
      out.write("    </footer>\n");
      out.write("  </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("<!-- 다크모드 토글 스크립트 -->\n");
      out.write("<script>\n");
      out.write("(function() {\n");
      out.write("  const themeToggle = document.getElementById('themeToggle');\n");
      out.write("  const themeIcon = document.getElementById('themeIcon');\n");
      out.write("  const html = document.documentElement;\n");
      out.write("  \n");
      out.write("  // 저장된 테마 또는 시스템 설정 확인\n");
      out.write("  const savedTheme = localStorage.getItem('theme');\n");
      out.write("  const systemDark = window.matchMedia('(prefers-color-scheme: dark)').matches;\n");
      out.write("  const initialTheme = savedTheme || (systemDark ? 'dark' : 'light');\n");
      out.write("  \n");
      out.write("  // 초기 테마 적용\n");
      out.write("  if (initialTheme === 'dark') {\n");
      out.write("    html.setAttribute('data-theme', 'dark');\n");
      out.write("    if (themeIcon) themeIcon.textContent = '☀️';\n");
      out.write("  }\n");
      out.write("  \n");
      out.write("  // 토글 버튼 클릭 이벤트\n");
      out.write("  if (themeToggle) {\n");
      out.write("    themeToggle.addEventListener('click', () => {\n");
      out.write("      const isDark = html.getAttribute('data-theme') === 'dark';\n");
      out.write("      \n");
      out.write("      if (isDark) {\n");
      out.write("        html.removeAttribute('data-theme');\n");
      out.write("        localStorage.setItem('theme', 'light');\n");
      out.write("        themeIcon.textContent = '🌙';\n");
      out.write("      } else {\n");
      out.write("        html.setAttribute('data-theme', 'dark');\n");
      out.write("        localStorage.setItem('theme', 'dark');\n");
      out.write("        themeIcon.textContent = '☀️';\n");
      out.write("      }\n");
      out.write("    });\n");
      out.write("  }\n");
      out.write("})();\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_sec_005fauthorize_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f0 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    _jspx_th_sec_005fauthorize_005f0.setPageContext(_jspx_page_context);
    _jspx_th_sec_005fauthorize_005f0.setParent(null);
    // /WEB-INF/views/includes/header.jsp(33,10) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sec_005fauthorize_005f0.setAccess("isAuthenticated()");
    int _jspx_eval_sec_005fauthorize_005f0 = _jspx_th_sec_005fauthorize_005f0.doStartTag();
    if (_jspx_eval_sec_005fauthorize_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      out.write("\n");
      out.write("            <span class=\"text-white\">\n");
      out.write("              <i class=\"bi bi-person-circle me-1\"></i>\n");
      out.write("              <strong>");
      if (_jspx_meth_sec_005fauthentication_005f0(_jspx_th_sec_005fauthorize_005f0, _jspx_page_context))
        return true;
      out.write("</strong>\n");
      out.write("            </span>\n");
      out.write("            <a href=\"/account/logout\" class=\"btn btn-sm btn-outline-light\">\n");
      out.write("              <i class=\"bi bi-box-arrow-right me-1\"></i>로그아웃\n");
      out.write("            </a>\n");
      out.write("          ");
    }
    if (_jspx_th_sec_005fauthorize_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f0);
    return false;
  }

  private boolean _jspx_meth_sec_005fauthentication_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  sec:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_sec_005fauthentication_005f0 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    _jspx_th_sec_005fauthentication_005f0.setPageContext(_jspx_page_context);
    _jspx_th_sec_005fauthentication_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f0);
    // /WEB-INF/views/includes/header.jsp(36,22) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sec_005fauthentication_005f0.setProperty("principal.username");
    int _jspx_eval_sec_005fauthentication_005f0 = _jspx_th_sec_005fauthentication_005f0.doStartTag();
    if (_jspx_th_sec_005fauthentication_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.reuse(_jspx_th_sec_005fauthentication_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent(null);
    // /WEB-INF/views/product/read.jsp(20,35) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.pictureurl}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f1.setParent(null);
    // /WEB-INF/views/product/read.jsp(22,75) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.name}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
    if (_jspx_th_c_005fout_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f2.setParent(null);
    // /WEB-INF/views/product/read.jsp(24,61) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.category}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
    if (_jspx_th_c_005fout_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f3(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f3.setParent(null);
    // /WEB-INF/views/product/read.jsp(27,43) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.num}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f3 = _jspx_th_c_005fout_005f3.doStartTag();
    if (_jspx_th_c_005fout_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatNumber_005f0.setParent(null);
    // /WEB-INF/views/product/read.jsp(30,68) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.price}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/views/product/read.jsp(30,68) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f0.setType("number");
    int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
    if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f4(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f4 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f4.setParent(null);
    // /WEB-INF/views/product/read.jsp(37,8) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.description}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f4 = _jspx_th_c_005fout_005f4.doStartTag();
    if (_jspx_th_c_005fout_005f4.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f4);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f5(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f5 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f5.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f5.setParent(null);
    // /WEB-INF/views/product/read.jsp(43,33) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f5.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.regid}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f5 = _jspx_th_c_005fout_005f5.doStartTag();
    if (_jspx_th_c_005fout_005f5.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f5);
    return false;
  }
}
