/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2026-01-05 06:40:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.product;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/works/SF/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/sp0/WEB-INF/lib/spring-security-taglibs-6.5.5.jar!/META-INF/security.tld", Long.valueOf(1758086692000L));
    _jspx_dependants.put("/WEB-INF/views/includes/footer.jsp", Long.valueOf(1767594467839L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-6.5.5.jar", Long.valueOf(1766461423263L));
    _jspx_dependants.put("/WEB-INF/views/includes/header.jsp", Long.valueOf(1767594467839L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\" />\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\n");
      out.write("  <title>Admin Panel</title>\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("  \n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\">\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("  <!-- Top Navbar -->\n");
      out.write("  <header class=\"header\">\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-custom px-4\">\n");
      out.write("      <a class=\"navbar-brand\" href=\"#\">관리자 페이지</a>\n");
      out.write("      <div class=\"collapse navbar-collapse\">\n");
      out.write("        <ul class=\"navbar-nav me-auto\">\n");
      out.write("          <li class=\"nav-item\"><a class=\"nav-link\" href=\"/product/list\">상품 리스트</a></li>\n");
      out.write("        </ul>\n");
      out.write("        <span class=\"navbar-text d-flex align-items-center gap-3\">\n");
      out.write("          <!-- 다크모드 토글 버튼 -->\n");
      out.write("          <button id=\"themeToggle\" class=\"btn btn-sm btn-outline-light\" title=\"테마 변경\">\n");
      out.write("            <span id=\"themeIcon\">🌙</span>\n");
      out.write("          </button>\n");
      out.write("          Logged in as <strong>admin</strong> | <a href=\"#\" class=\"text-white text-decoration-underline\">Logout</a>\n");
      out.write("        </span>\n");
      out.write("      </div>\n");
      out.write("    </nav>\n");
      out.write("  </header>\n");
      out.write("\n");
      out.write("  <!-- Sidebar + Content -->\n");
      out.write("  <div class=\"main-wrapper\">\n");
      out.write("    <!-- Sidebar -->\n");
      out.write("    <div class=\"sidebar pt-3\">\n");
      out.write("      <div class=\"list-group list-group-flush\">\n");
      out.write("        <a href=\"/product/list\" class=\"list-group-item active\">상품 리스트</a>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Main Content -->\n");
      out.write("    <div class=\"content\">    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row justify-content-center\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"card shadow mb-4\">\r\n");
      out.write("                        <div class=\"card-header py-3\">\r\n");
      out.write("                            <h6 class=\"m-0 font-weight-bold text-primary\">Product Register</h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <form action=\"/product/register\" method=\"post\" enctype=\"multipart/form-data\" class=\"p-3\">\r\n");
      out.write("                                <div class=\"mb-3\">\r\n");
      out.write("                                    <label class=\"form-label\">Product Name</label>\r\n");
      out.write("                                    <input type=\"text\" name=\"name\" class=\"form-control\" required>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"mb-3\">\r\n");
      out.write("                                    <label class=\"form-label\">Category</label>\r\n");
      out.write("                                    <input type=\"text\" name=\"category\" class=\"form-control\">\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"mb-3\">\r\n");
      out.write("                                    <label class=\"form-label\">Price</label>\r\n");
      out.write("                                    <input type=\"number\" name=\"price\" class=\"form-control\" required>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"mb-3\">\r\n");
      out.write("                                    <label class=\"form-label\">Description</label>\r\n");
      out.write("                                    <textarea class=\"form-control\" name=\"description\" rows=\"3\"></textarea>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"mb-3\">\r\n");
      out.write("                                    <label class=\"form-label\">상품 이미지</label>\r\n");
      out.write("                                    <input type=\"file\" name=\"imageFile\" class=\"form-control\" accept=\"image/*\">\r\n");
      out.write("                                    <div id=\"imagePreview\" class=\"mt-2\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"mb-3\">\r\n");
      out.write("                                    <label class=\"form-label\">Register ID</label>\r\n");
      out.write("                                    <input type=\"text\" name=\"regid\" class=\"form-control\" />\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"d-flex justify-content-end\">\r\n");
      out.write("                                    <button type=\"submit\" class=\"btn btn-primary btn-lg\">Submit</button>\r\n");
      out.write("                                    <a href=\"/product/list\" class=\"btn btn-secondary btn-lg ms-2\">Cancel</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </form>\r\n");
      out.write("\r\n");
      out.write("                            <script>\r\n");
      out.write("                                // 이미지 미리보기\r\n");
      out.write("                                document.querySelector('input[name=\"imageFile\"]').addEventListener('change', function(e) {\r\n");
      out.write("                                    const preview = document.getElementById('imagePreview');\r\n");
      out.write("                                    preview.innerHTML = '';\r\n");
      out.write("                                    \r\n");
      out.write("                                    if (this.files && this.files[0]) {\r\n");
      out.write("                                        const reader = new FileReader();\r\n");
      out.write("                                        reader.onload = function(e) {\r\n");
      out.write("                                            preview.innerHTML = '<img src=\"' + e.target.result + '\" style=\"max-width:200px; max-height:200px; border-radius:8px;\">';\r\n");
      out.write("                                        }\r\n");
      out.write("                                        reader.readAsDataURL(this.files[0]);\r\n");
      out.write("                                    }\r\n");
      out.write("                                });\r\n");
      out.write("                            </script>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            ");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- Footer -->\n");
      out.write("    <footer class=\"footer py-3 mt-auto text-center\">\n");
      out.write("      <span class=\"text-muted\">&copy; 2026 관리자 페이지. All rights reserved.</span>\n");
      out.write("    </footer>\n");
      out.write("  </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("<!-- 다크모드 토글 스크립트 -->\n");
      out.write("<script>\n");
      out.write("(function() {\n");
      out.write("  const themeToggle = document.getElementById('themeToggle');\n");
      out.write("  const themeIcon = document.getElementById('themeIcon');\n");
      out.write("  const html = document.documentElement;\n");
      out.write("  \n");
      out.write("  // 저장된 테마 또는 시스템 설정 확인\n");
      out.write("  const savedTheme = localStorage.getItem('theme');\n");
      out.write("  const systemDark = window.matchMedia('(prefers-color-scheme: dark)').matches;\n");
      out.write("  const initialTheme = savedTheme || (systemDark ? 'dark' : 'light');\n");
      out.write("  \n");
      out.write("  // 초기 테마 적용\n");
      out.write("  if (initialTheme === 'dark') {\n");
      out.write("    html.setAttribute('data-theme', 'dark');\n");
      out.write("    if (themeIcon) themeIcon.textContent = '☀️';\n");
      out.write("  }\n");
      out.write("  \n");
      out.write("  // 토글 버튼 클릭 이벤트\n");
      out.write("  if (themeToggle) {\n");
      out.write("    themeToggle.addEventListener('click', () => {\n");
      out.write("      const isDark = html.getAttribute('data-theme') === 'dark';\n");
      out.write("      \n");
      out.write("      if (isDark) {\n");
      out.write("        html.removeAttribute('data-theme');\n");
      out.write("        localStorage.setItem('theme', 'light');\n");
      out.write("        themeIcon.textContent = '🌙';\n");
      out.write("      } else {\n");
      out.write("        html.setAttribute('data-theme', 'dark');\n");
      out.write("        localStorage.setItem('theme', 'dark');\n");
      out.write("        themeIcon.textContent = '☀️';\n");
      out.write("      }\n");
      out.write("    });\n");
      out.write("  }\n");
      out.write("})();\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
